apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  destination:
    namespace: helm-jenkins
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: jenkins-helm
    repoURL: https://ussnorma.github.io/helm-releases/
    targetRevision: 0.1.0
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
