apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2024-03-11T19:19:34Z"
  generation: 14
  name: test
  namespace: argocd
  resourceVersion: "4574452"
  uid: 9a74f72f-c7d6-4bf7-9259-93f985932e97
spec:
  destination:
    namespace: helm-jenkins
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: jenkins-helm
    repoURL: https://ussnorma.github.io/helm-releases/
    targetRevision: 0.1.0
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
  - deployStartedAt: "2024-03-11T19:19:34Z"
    deployedAt: "2024-03-11T19:19:35Z"
    id: 0
    revision: 0.1.0
    source:
      chart: jenkins-helm
      repoURL: https://ussnorma.github.io/helm-releases/
      targetRevision: 0.1.0
  operationState:
    finishedAt: "2024-03-11T19:19:35Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        prune: true
        revision: 0.1.0
        syncOptions:
        - CreateNamespace=true
    phase: Succeeded
    startedAt: "2024-03-11T19:19:34Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: ConfigMap
        message: configmap/basic-security created
        name: basic-security
        namespace: helm-jenkins
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ConfigMap
        message: configmap/jenkins-config created
        name: jenkins-config
        namespace: helm-jenkins
        status: Synced
        syncPhase: Sync
        version: v1
      - group: rbac.authorization.k8s.io
        hookPhase: Running
        kind: ClusterRoleBinding
        message: "clusterrolebinding.rbac.authorization.k8s.io/helm-jenkins reconciled.
          reconciliation required create\n\tmissing subjects added:\n\t\t{Kind:ServiceAccount
          APIGroup: Name:default Namespace:helm-jenkins}. clusterrolebinding.rbac.authorization.k8s.io/helm-jenkins
          configured. Warning: resource clusterrolebindings/helm-jenkins is missing
          the kubectl.kubernetes.io/last-applied-configuration annotation which is
          required by  apply.  apply should only be used on resources created declaratively
          by either  create --save-config or  apply. The missing annotation will be
          patched automatically."
        name: helm-jenkins
        namespace: helm-jenkins
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/helm-jenkins created
        name: helm-jenkins
        namespace: helm-jenkins
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/helm-jenkins created
        name: helm-jenkins
        namespace: helm-jenkins
        status: Synced
        syncPhase: Sync
        version: v1
      - group: networking.k8s.io
        hookPhase: Running
        kind: Ingress
        message: ingress.networking.k8s.io/ingress-helm-jenkins created
        name: ingress-helm-jenkins
        namespace: helm-jenkins
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 0.1.0
      source:
        chart: jenkins-helm
        repoURL: https://ussnorma.github.io/helm-releases/
        targetRevision: 0.1.0
  reconciledAt: "2024-03-11T19:19:35Z"
  resources:
  - kind: ConfigMap
    name: basic-security
    namespace: helm-jenkins
    status: Synced
    version: v1
  - kind: ConfigMap
    name: jenkins-config
    namespace: helm-jenkins
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: helm-jenkins
    namespace: helm-jenkins
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: helm-jenkins
    namespace: helm-jenkins
    status: Synced
    version: v1
  - group: networking.k8s.io
    health:
      status: Healthy
    kind: Ingress
    name: ingress-helm-jenkins
    namespace: helm-jenkins
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: helm-jenkins
    status: Synced
    version: v1
  sourceType: Helm
  summary:
    externalURLs:
    - http://helm-jenkins.k8s-9.sa/
    images:
    - jfrog.it-academy.by/public/jenkins-ci:kononkov
  sync:
    comparedTo:
      destination:
        namespace: helm-jenkins
        server: https://kubernetes.default.svc
      source:
        chart: jenkins-helm
        repoURL: https://ussnorma.github.io/helm-releases/
        targetRevision: 0.1.0
    revision: 0.1.0
    status: Synced
