apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs
  namespace: argocd
spec:
  destination:
    namespace: nfs-provisioner
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: nfs-subdir-external-provisioner
    repoURL: https://ussnorma.github.io/helm-releases/
    targetRevision: 4.0.18
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true