apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  destination:
    namespace: pre-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: wordpress-helm
    repoURL: https://ussnorma.github.io/helm-releases/
    targetRevision: 20.1.2
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true